### ISSUE TITLE
Falscher Steig für Nachtautobusse

### ISSUE THREAD

**Issue by anlumo** [Metalab/oeffimonitor#10]
Die Station für die meisten Nachtautobusse (N66, N38, N25, N60, …) ist Rathausplatz/Burgtheater, nicht Schottentor. Schottentor würde ich entfernen.

**Comment by burnoutberni** [comment]
I guess/hope this is fixed with hetti's latest pull request.

**Comment by anlumo** [comment]
Fix has disappeared again, probably reverted by accident at some point.

**Comment by burnoutberni** [comment]
Hab gelesen, dass der Öffimonitor im Lab wieder läuft. Ist dieses Issue damit gefixt? // @anlumo @wilhelmy

**Comment by anlumo** [comment]
Ja, die Station ist jetzt drin!
