### ISSUE TITLE
N60 hält neben Schottentor auch am Rathausplatz/Burgtheater, das ist näher

### ISSUE THREAD

**Issue by wilhelmy** [Metalab/oeffimonitor#12]

**Comment by Hetti** [comment]
Ich hatte das schon eingebaut gehabt für den N66.

Siehe: https://github.com/Metalab/oeffimonitor/commit/7fedd0d407cefbc0cbe0073487690839ecc16dff

Du müsstest nur noch die Linie N60 und evtl. die anderen Nachtlinien auch noch :)

**Comment by burnoutberni** [comment]
Hab gerade #22 gemergt, wie @schwindp richtig erkannt hat, sollte die RBL 17 alle Linien in die Richtung catchen, also auch den N60er. Ich mach das Issue mal zu.
