### ISSUE TITLE
Pull-Request aus geforktem Repo

### ISSUE THREAD

**Issue by maltezacharias** [Metalab/oeffimonitor#14]
Hi,

ich hab auf der Basis eures Öffimonitors etwas ähnliches für meine WG gebaut und dafür einen Fork erstellt (https://github.com/maltezacharias/oeffimonitor).

Ich würde es cool finden, wenn ihr meine Änderungen übernehmen würdet. Da ich aber relativ viel umgebaut habe wollte ich vorher einmal nachfragen ob's noch Sachen gibt, die ich vor einem Merge wieder anpassen müsste. Im wesentlichen sind in meinem Fork folgende Änderungen:
- API Response Cache als eigenes Node-Module strukturiert
- Express Framework fürs Routing und die Request-Bearbeitung
- Pug zum Rendern der Frontendseiten
- Css konfigurierbar per settings.js
- Neues alternatives CSS für eInk Reader (mein Anwendungsfall), per settings steuerbar
- Wettervorhersage (im metalab.css noch nicht gestylt, könnte man auch ausblenden)
- Den ARC robuster gemacht (+timeout, +error Handling, +logging)

Ich hab mittlerweile das Gefühl, dass das Ergebnis recht robust läuft und im wesentlichen ist euer Code erhalten geblieben. Die Wettervorhersage zieht Daten von openweathermap.org und wird über ein SVG angezeigt dass per Javascript manipuliert wird.

Frontend-Code hat keine neuen Dependencies, im Backend habe ich folgende Deps eingebaut:
    "body-parser": "^1.15.1",
    "debug": "^2.2.0",
    "express": "^4.13.4",
    "lodash": "^4.13.1",
    "morgan": "^1.7.0",
    "pug": "^2.0.0-alpha8",
    "serve-favicon": "^2.3.0",
    "when": "^3.7.7"

Ich tippe mal, dass ihr absichtlich ne Minimallösung gebaut habt was Dependencies angeht, aber gerade auf Serverseite fand ich das sehr hilfreich diese zu verwenden. Was meint ihr? 

Screenshot:
![image](https://cloud.githubusercontent.com/assets/9914287/15957946/ab0d431e-2ef2-11e6-8756-51d293a1e6c3.png)

**Comment by maltezacharias** [comment]
(Die Spalten/Felder die in der Tabelle fehlen sind nur in meinem CSS für meinen eInk-Reader ausgeblendet, im metalab Design snid sie nach wie vor vorhanden)

**Comment by wilhelmy** [comment]
Naja, das mit der Minimallösung stimmt schon. Aber ich werd's mir mal genau anschauen. Wenn wir dann mehr Dependencies einbauen werde ich drüber nachdenken auch den ES6-code von Jascha zu mergen, bzw gleich ES6 zu verwenden (ich wollte eigentlich damit warten bis ES6 soweit "üblich" ist, dass ich kein babel mehr brauche) - Jascha hat damals auch etlich viele Dependencies mit eingebaut :)

Beim Drüberschauen ist mir aufgefallen, dass deine Änderungen eigentlich schon Sinn machen, aber ich kenne teilweise die Libraries nicht die du verwendest - ich kenne mich mit node nur oberflächlich aus und habe den Öffimonitor damals in JS geschrieben, damit es einfacher für andere ist, mitzumachen, nachdem der Frontend-Code eh auch in JS geschrieben ist. Blöderweise macht es das für mich selbst an dieser Stelle ein bisschen komplizierter, aber okay ;)

Außerdem ist die Indentation teilweise kaputt, was daran liegt, dass Tabs und Spaces gemischt sind. Ich hatte für das Backend Tabs verwendet.

Von einigen Leuten im Lab kam auch sowas wie "Hey, cooles Projekt, ich mag es wegwerfen und stattdessen den Infoscreen vom CCC nehmen und anpassen" - ich weiß also nicht wie permanent das Ganze ist, aber Teile des Codes kann man dafür vielleicht auch wiederverwenden. Ich hatte auch an etwas Flipscreen ähnliches gedacht, was zwischen verschiedenen Displays mit Informationen hin- und herwechselt. (und dafür hätte der CCC scheinbar schon fertigen, getesteten Code wo ich den Öffimonitor nur als Plugin umschreiben müsste)

Hast du den Server auch auf deinem nook laufen? (Einer deiner Kommentare erwähnt alte nodejs Versionen für ARM - meinst du einen nook build?)

Insgesamt cooles Projekt, ich denke jetzt selbst darüber nach, meinen nook in der WG aufzuhängen und mir einen neuen eInk-Reader zu kaufen, weil das Android auf dem nook schon irgendwie ziemlich alt ist.

Schau mal im Lab vorbei? :)

**Comment by maltezacharias** [comment]
ES6 hatte ich zuerst auch, aber dann gesehen, dass das auf Node v0.12.0 irgendwie noch nicht läuft.. Deshalb habe ich das dann auch erstmal zurückgestellt. Ich hab den Server auf einem echten Linux-Server laufen, den ich eh als Fileserver rumstehen hab, aber nach oberflächlichem Googlen hatte ich den Eindruck, dass es für den Raspi den ihr benutzt wahrscheinlich nicht so einfach eine aktueller Node Version gibt und deshalb den Code so gelassen dass er auf v0.12.0 läuft. Also für mich kann es auch ES6 sein :) 

body-parser": "^1.15.1", --> Express-Dependency, parst Requests. Wird noch nicht benutzt. 
"debug": "^2.2.0", --> Rel. einfache Logging API
"express": "^4.13.4", --> die Standard-Lib in Node für Webserver, übernimmt z.B. das routing, ermöglicht das leichte Verwenden von Middleware (z.B. Logger, Rendering-Libs wie pug (früher Jade), ...)
"lodash": "^4.13.1", --> Könnte noch raus, wird nur einmal benutzt, Util-Lib mit Methoden wie _.each _.union, ... für Bearbeitung/Arbeiten mit Arrays
"morgan": "^1.7.0", --> Logger für Express, produziert auf STDOUT ein Log der Requests
"pug": "^2.0.0-alpha8", --> Rendert die dynamische Seite ( server/views/index.pug )
"serve-favicon": "^2.3.0", -> Benutzt Express um das favicon zu cachen
"when": "^3.7.7" --> Ups, benutze ich im Moment gar nicht, theoretisch kann man damit Promise-basierte Callbacks bauen

Ich _dachte_ ich hätte auch Tabs genommen, wenn das kaputt ist schaue ich nochmal drüber. Das nervt mich auch immer wenn das gemischt ist :) Ich hab aber auch mit Atom, Nano, mcedit, ... die Dateien editiert, kann gut sein, dass da einer Mist gebaut hat ;)

CCC-Infoscreen: Kenne ich auch noch nicht, der Oeffimonitor war für mich genau das was ich gesucht habe und gut hackbar ;)

Also das mit dem Nook ist eigentlich ganz nett, Manchmal macht aber der Opera-Browser seltsame Sachen und ich muss per Hand refreshen. Im Log sehe ich auch manchmal einen Pile-Up der Requests. Anbringen mit Klettband hat sich bewährt.

Metalab vorbeischauen: Gerne, wann bist du denn mal dort? Hatte auch schon mal mit @burnoutberni gemailt zum Oeffimonitor.

**Comment by maltezacharias** [comment]
Soo... Das Tab-Problem hab ich gelöst. Hatte den Editor falsch eingestellt :/

**Comment by wilhelmy** [comment]
Es gibt Nightly builds für armv7l: https://nodejs.org/download/nightly/v7.0.0-nightly20160609a766ebf594/

Wir haben derzeit node v4.2.1 am raspi laufen.

**Comment by wilhelmy** [comment]
Danke übrigens für die ausführliche Erklärung zu den Modulen. Ich bin fast jeden Tag im Lab, unter der Woche eher Abends und Nachts, am Wochenende auch tagsüber.

**Comment by maltezacharias** [comment]
Ah cool, ja dann werd ich heute Abend die Dependencies auf lodash und when ausbauen und nochmal die Änderungen für das 0.12er wieder rauswerfen und testen ob ich was neues kaputt gemacht habe :)

**Comment by maltezacharias** [comment]
Okay, fertig gebastelt, pull request ist da ;)
close in favor of https://github.com/Metalab/oeffimonitor/pull/15
