### ISSUE TITLE
Clock broken?

### ISSUE THREAD

**Issue by burnoutberni** [Metalab/oeffimonitor#17]
Needs clarification.

https://metalab.at/issues/ticket/450#ticket

**Comment by burnoutberni** [comment]
Someone should check if the bug is fixed with the last commit. /cc @wilhelmy

**Comment by wilhelmy** [comment]
Well, the fix looks good but I can't really test from here :)

See the internal mailing list for instructions about updating the production system - alternatively I'll take a look in January.
