### ISSUE TITLE
N49 fehlt

### ISSUE THREAD

**Issue by wilhelmy** [Metalab/oeffimonitor#2]

**Comment by burnoutberni** [comment]
tried to solve this, but wasn't able to find the corresponding "rbl" id
Sources: Wiener Linien API [csv-haltestellen](https://www.data.gv.at/katalog/dataset/wiener-linien-echtzeitdaten/resource/875efc25-0bc7-4a4f-a7af-f973c890e6b8), [csv-steige](https://www.data.gv.at/katalog/dataset/wiener-linien-echtzeitdaten/resource/1ee94f81-86d4-47ea-84a6-257cccb4672e)

**Comment by wilhelmy** [comment]
I think Hetti fixed this?

**Comment by anlumo** [comment]
Correct
