### ISSUE TITLE
All API-related links as broken in the README

### ISSUE THREAD

**Issue by endreszabo** [Metalab/oeffimonitor#27]
All API-related links as broken in the README.md. I'll come up with a PR if I find their current URLs.

**Comment by skauk** [comment]
@endreszabo https://www.data.gv.at/katalog/dataset/522d3045-0b37-48d0-b868-57c99726b1c4#resources

**Comment by Hetti** [comment]
just fixed it ;-)
thanks @rcknr for the link!
