### ISSUE TITLE
Only run one FOSSGIS request per coordinate

### ISSUE THREAD

**Issue by Hetti** [Metalab/oeffimonitor#30]
Currently multiple requests are issued for the same coordinates in the code, for the walking distance time calculation.

![image](https://github.com/Metalab/oeffimonitor/assets/3261408/938faca2-27b1-47dc-9145-96ee0369d9fa)

It makes sense to only run the request once per coordinate and also adhere to the policy with 1 second per request as mentioned in #29

**Comment by Hetti** [comment]
to clarify:
as the coordinates of the stations and the offiemonitor do not change, it should be enough to only pull one time the walking distances for all coordinates on bootup from the FOSSGIS Server and not every time when updating the schedule.

For further requests the walking times can be obtained from the local "database" then.

**Comment by burnoutberni** [comment]
Should be fixed with #31, pls reopen if it persists.
