### ISSUE TITLE
Fehlende API-Responses anzeigen

### ISSUE THREAD

**Issue by wilhelmy** [Metalab/oeffimonitor#5]
Wenn der Server keine responses liefert, bleibt im Client das display gleich - die Uhrzeit läuft aber weiter(?)

Warnung anzeigen, wenn die Daten zu alt werden um nützlich zu sein.

**Comment by anlumo** [comment]
Generell sollte er lokal die relativen Abfahrtszeiten runterzählen und abgelaufene autonom entfernen. Damit würde das Problem sich von alleine beheben, weil die Liste dann leer ist.

**Comment by wilhelmy** [comment]
Nini zeigt eine Warnung an wenn keine Response vom Server kommt.
Das runterzählen implementiere ich dann sobald Jaschas Branch gemerged ist... sonst wird der Merge zu umständlich.
