### ISSUE TITLE
implement css preprocessor

### ISSUE THREAD

**Issue by jaeh** [Metalab/oeffimonitor#8]
i would really like to have css/html preprocessing in the toolchain,

CSS: 
1. [stylus](https://learnboost.github.io/stylus) which i would prefer but needs additional knowledge from devs.
2. [autoprefixer](https://www.npmjs.com/package/autoprefixer) which only adds browser prefixes but does not have syntactic sugar like variables and mixins, which stylus has.

HTML:
1. [jade](http://jade-lang.com/) syntax is very close to stylus, making it the perfect match ;)

thoughts?

**Comment by jaeh** [comment]
wanted to add all of us to make sure you get the notifications, not possible :|

anyways, you both should have gotten notifications now :p

**Comment by wilhelmy** [comment]
We did, but I guess watching the repo is enough in order to get notified :)
Just didn't check my github account for a while

**Comment by burnoutberni** [comment]
To actually address your proposal: not sure if that actually fits.

I do agree that e.g. browser prefixes are a pain in the ass, but we have a negligable amount of html/css in the project and especially if we take into account that when @wilhelmy started this, they aimed for zero dependencies, I don't see a huge benefit in all of that preprocessing magic for a project of this size.

(But then again, it's a Metalab project, so if you want to have this, just do it.)
